### ISSUE TITLE
许可证问题

### ISSUE THREAD

**Issue by 0xd1cf001e** [WanhuKarrot/CZ-5#1]
forum上写的是CC-BY-NC-ND 4.0 但是github上的是Apache-2.0，望修正

**Comment by WanhuKarrot** [comment]
Thank you very much and I will correct it in 12 hours.------------------ 原始邮件 ------------------
发件人: "WC12366"<notifications@github.com>
发送时间: 2020年3月3日(星期二) 中午11:18
收件人: "WanhuKarrot/CZ-5"<CZ-5@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [WanhuKarrot/CZ-5] 许可证问题 (#1)



forum上写的是CC-BY-NC-ND 4.0 但是github上的是Apache-2.0，望修正
 
&mdash;

**Comment by WanhuKarrot** [comment]
How to choose the correct licence. I have not find the CC-BY-NC-ND 4.0 in github. Is it has a nickname or so?

**Comment by 0xd1cf001e** [comment]
直接把cc协议的原文全部复制到license文件里就行了

**Comment by WanhuKarrot** [comment]
Okay, thank u very much.
